### ISSUE TITLE
Extensions – OfficeViewer, Excel and PowerPoint buttons load Word file

### ISSUE THREAD

**Issue by paulcordova** [iceteagroup/Wisej-DemoBrowser#58] opened 2022-04-26 03:19 UTC
![image](https://user-images.githubusercontent.com/7750628/165213503-e25e4090-c282-430d-84b8-67aba0b9b4a8.png)

**Comment by AlaaTrAce** [comment] 2022-04-26 04:16
Duplicate of https://github.com/iceteagroup/Wisej-DemoBrowser/issues/45

**Closed by AlaaTrAce** 2022-04-26 04:16 UTC
Labels: duplicate, invalid
